name: wunderbuy
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.4.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  #utility management
  http: ^1.1.0
  intl: ^0.18.1
  logger: ^2.0.1
  url_launcher: ^6.1.12
  #icons
  iconsax: ^0.0.8
  cupertino_icons: ^1.0.6
  #state management
  get: ^4.6.6
  get_storage: ^2.1.1
  


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets: 
    - assets/fonts/
    - assets/icons/
    - assets/images/
